# Generated by Django 6.0.7 on 2026-07-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('NORMAL', 'Normal'), ('VIP', 'VIP'), ('SLEEPER', 'Sleeper')], default='NORMAL', max_length=20)),
                ('is_window', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bus.bus')),
            ],
            options={
                'db_table': 'seat',
                'ordering': ['seat_number'],
                'constraints': [models.UniqueConstraint(fields=('bus', 'seat_number'), name='unique_bus_seat')],
            },
        ),
    ]
