# Generated by Django 6.0.7 on 2026-07-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(choices=[('KOSHI', 'Koshi'), ('MADESH', 'Madhesh'), ('BAGMATI', 'Bagmati'), ('GANDAKI', 'Gandaki'), ('LUMBINI', 'Lumbini'), ('KARNALI', 'Karnali'), ('SUDURPASCHIM', 'Sudurpaschim')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'city',
                'ordering': ['name'],
            },
        ),
    ]
