# Generated by Django 6.0.7 on 2026-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='col',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
