# Generated by Django 6.0.7 on 2026-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0002_seat_col_seat_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
