# Generated by Django 6.0.7 on 2026-07-25 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiace_name', models.CharField(max_length=100)),
                ('hiace_number', models.CharField(max_length=50, unique=True)),
                ('hiace_type', models.CharField(choices=[('AC', 'AC'), ('NON_AC', 'Non AC')], max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('seat_layout', models.JSONField(default=dict)),
                ('wifi', models.BooleanField(default=False)),
                ('charging', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='hiace_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hiace',
                'ordering': ['hiace_name'],
            },
        ),
        migrations.CreateModel(
            name='HiaceRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in KM', max_digits=8)),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_destination_routes', to='city.city')),
                ('hiace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_routes', to='hiace.hiace')),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='hiace_routes', to=settings.AUTH_USER_MODEL)),
                ('source_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_source_routes', to='city.city')),
            ],
            options={
                'db_table': 'hiace_route',
                'ordering': ['source_city', 'destination_city'],
            },
        ),
        migrations.CreateModel(
            name='HiaceRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('arrival_offset', models.DurationField(help_text='Time from source')),
                ('departure_offset', models.DurationField(help_text='Time from source')),
                ('is_boarding', models.BooleanField(default=True)),
                ('is_dropping', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='hiace.hiaceroute')),
            ],
            options={
                'db_table': 'hiace_route_stop',
                'ordering': ['stop_order'],
                'unique_together': {('route', 'stop_order')},
            },
        ),
        migrations.CreateModel(
            name='HiaceRouteFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='hiace.hiaceroute')),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_fare_from', to='hiace.hiaceroutestop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_fare_to', to='hiace.hiaceroutestop')),
            ],
            options={
                'db_table': 'hiace_route_fare',
            },
        ),
        migrations.CreateModel(
            name='HiaceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_schedules', to='hiace.hiaceroute')),
            ],
            options={
                'db_table': 'hiace_schedule',
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HiaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=30, unique=True)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('platform_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='hiace_booking_qr/')),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_bookings', to=settings.AUTH_USER_MODEL)),
                ('boarding_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiace_boarding_bookings', to='hiace.hiaceroutestop')),
                ('dropping_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiace_dropping_bookings', to='hiace.hiaceroutestop')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_bookings', to='hiace.hiaceschedule')),
            ],
            options={
                'db_table': 'hiace_booking',
            },
        ),
        migrations.CreateModel(
            name='HiaceSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('NORMAL', 'Normal'), ('VIP', 'VIP')], default='NORMAL', max_length=20)),
                ('row', models.PositiveIntegerField(default=1)),
                ('col', models.PositiveIntegerField(default=1)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_window', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_seats', to='hiace.hiace')),
            ],
            options={
                'db_table': 'hiace_seat',
                'ordering': ['seat_number'],
            },
        ),
        migrations.CreateModel(
            name='HiaceBookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiace_booking_seats', to='hiace.hiacebooking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiace.hiaceseat')),
            ],
            options={
                'db_table': 'hiace_booking_seat',
            },
        ),
        migrations.AddConstraint(
            model_name='hiaceseat',
            constraint=models.UniqueConstraint(fields=('hiace', 'seat_number'), name='unique_hiace_seat'),
        ),
        migrations.AddConstraint(
            model_name='hiacebookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat'), name='unique_hiace_booking_seat'),
        ),
    ]
