# Generated by Django 6.0.7 on 2026-09-15 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiace', '0002_hiace_hiaceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiacebooking',
            name='qr_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
    ]
