# Generated by Django 6.0.7 on 2026-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiace', '0003_alter_hiacebooking_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiacebooking',
            name='departure_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
