# Generated by Django 6.0.7 on 2026-09-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_routefare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routefare',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='routes.route'),
        ),
    ]
