# Generated by Django 6.0.7 on 2026-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_expired_at_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platform_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='booking_qr/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
