# Generated by Django 6.0.7 on 2026-07-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_platform_amount_booking_qr_code_and_more'),
        ('routes', '0002_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boarding_stop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='boarding_bookings', to='routes.routestop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='dropping_stop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='dropping_bookings', to='routes.routestop'),
            preserve_default=False,
        ),
    ]
