# Generated by Django 6.0.7 on 2026-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
