# Generated by Django 6.0.7 on 2026-07-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='fare',
        ),
    ]
