# Generated by Django 6.0.7 on 2026-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, unique=True)),
                ('minimum_version', models.CharField(max_length=20)),
                ('latest_version', models.CharField(max_length=20)),
                ('mandatory', models.BooleanField(default=True)),
                ('store_url', models.URLField()),
                ('update_message', models.TextField(default='A new version of the app is available. Please update to continue.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Version Config',
                'verbose_name_plural': 'App Version Config',
            },
        ),
    ]
