# Generated by Django 6.0.7 on 2026-07-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eticketauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
