# Generated by Django 6.0.7 on 2026-07-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticketauth', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
