# Generated by Django 6.0.7 on 2026-08-08 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_boarding_stop_booking_dropping_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='qr_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
    ]
