# Generated by Django 6.0.7 on 2026-07-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticketauth', '0003_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
