# Generated by Django 6.0.7 on 2026-10-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticketauth', '0006_alter_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
