# Generated by Django 6.0.7 on 2026-07-11 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=50, unique=True)),
                ('bus_type', models.CharField(choices=[('AC', 'AC'), ('NON_AC', 'Non AC'), ('DELUXE', 'Deluxe'), ('VIP', 'VIP'), ('SLEEPER', 'Sleeper')], max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('seat_layout', models.JSONField(default=dict)),
                ('wifi', models.BooleanField(default=False)),
                ('charging', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
