# Generated by Django 6.0.7 on 2026-08-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='busimage',
            field=models.ImageField(blank=True, null=True, upload_to='busimage'),
        ),
    ]
